name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm i -g yarn

      - name: Setup test project
        run: |
          npx create-react-app test-app
          cd test-app

          yarn add file:..

          sed -i 's/react-scripts start/cra-preact start/g' package.json
          sed -i 's/react-scripts build/cra-preact build/g' package.json
          sed -i 's/react-scripts test/cra-preact test/g' package.json

          cd ..
        env:
          CI: true

      - name: Testing
        run: |
          cd test-app

          # ok!
          yarn test
          yarn build

          # bad!
          if yarn cra-react eject 2> /dev/null ; then
            exit 1
          fi
          if yarn cra-react random-arg 2> /dev/null ; then
            exit 1
          fi
        env:
          CI: true
